workspace = { members = ["electrum_engine_macros"] }
[package]
name = "electrum_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.79"
glam = "0.25.0"
vulkanalia = { version = "0.22.0", features = ["libloading", "window"] }
shaderc = "0.8.3"
thiserror = "1.0.56"
tobj = { version = "4.0.0", features = ["log"] }
tracing = "0.1.40"
winit = "0.28.7"
image = "0.24.9"

electrum_engine_macros = { path = "electrum_engine_macros"}

[dev-dependencies]
tracing-subscriber = "0.3.18"
